services:
  aitavalida:
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.aitavalida.rule=Host(`aitavalida.azib.net`)"
      - "traefik.http.routers.aitavalida.entrypoints=websecure"
      - "traefik.http.routers.aitavalida.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true
